sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t iamrahulrnair/docker-react .
script:
  - docker container run -e CI=true iamrahulrnair/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-846463688383'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
